var searchData=
[
  ['w',['w',['../struct_ovr_1_1_sizei.html#a493254d63cb13a4abcb5d279459e2f5a',1,'Ovr.Sizei.w()'],['../struct_ovr_1_1_quatf.html#ad15e8a82bea7d23d2ab95e7edec1b0b0',1,'Ovr.Quatf.w()']]],
  ['waitforendofframe',['waitForEndOfFrame',['../class_o_v_r_manager.html#a6f29a0569a6740cbf1d608bc906cea2d',1,'OVRManager']]],
  ['waittilltime',['WaitTillTime',['../class_ovr_1_1_hmd.html#af93f3d51654e3c884fadb854a85cd2be',1,'Ovr::Hmd']]],
  ['walkanimation',['walkAnimation',['../_third_person_controller_8js.html#a1a5bfcbaec7da739a4d3d2b20c903234',1,'ThirdPersonController.js']]],
  ['walking',['Walking',['../_third_person_controller_8js.html#aacbb008a93d24b04a8779bbdbd8880b5a7632ff25e7a1c2e6df8c2003b738fe72',1,'ThirdPersonController.js']]],
  ['walkmaxanimationspeed',['walkMaxAnimationSpeed',['../_third_person_controller_8js.html#a4a5cd815b03ef0435468ac3c92531275',1,'ThirdPersonController.js']]],
  ['walkspeed',['walkSpeed',['../_third_person_controller_8js.html#ac0c1a633d51bbdb6226e90e4c83fd42b',1,'ThirdPersonController.js']]],
  ['walktimestart',['walkTimeStart',['../_third_person_controller_8js.html#ab4a3b480f2907929002f452c84ebea4c',1,'ThirdPersonController.js']]],
  ['washmdpresent',['wasHmdPresent',['../class_o_v_r_manager.html#a71b333338b960a89175fbc1c4a197659',1,'OVRManager']]],
  ['waspositiontracked',['wasPositionTracked',['../class_o_v_r_manager.html#a8cb391ebcc1c54e83701f9b990707a5c',1,'OVRManager']]],
  ['watersimple',['WaterSimple',['../class_water_simple.html',1,'']]],
  ['watersimple_2ecs',['WaterSimple.cs',['../_water_simple_8cs.html',1,'']]],
  ['widget',['Widget',['../jquery_8js.html#ac118a4c29a2ace98e4c956a7e504390d',1,'Widget():&#160;jquery.js'],['../jquery_8js.html#a4af68ff81d322a2563861409a79ff5bf',1,'widget(&quot;ui.mouse&quot;,{options:{cancel:&quot;:input,option&quot;, distance:1, delay:0}, _mouseInit:function(){var d=this;this.element.bind(&quot;mousedown.&quot;+this.widgetName, function(e){return d._mouseDown(e)}).bind(&quot;click.&quot;+this.widgetName, function(e){if(true===b.data(e.target, d.widgetName+&quot;.preventClickEvent&quot;)){b.removeData(e.target, d.widgetName+&quot;.preventClickEvent&quot;);e.stopImmediatePropagation();return false}});this.started=false}, _mouseDestroy:function(){this.element.unbind(&quot;.&quot;+this.widgetName)}, _mouseDown:function(f){if(a){return}(this._mouseStarted &amp;&amp;this._mouseUp(f));this._mouseDownEvent=f;var e=this, g=(f.which==1), d=(typeof this.options.cancel==&quot;string&quot;&amp;&amp;f.target.nodeName?b(f.target).closest(this.options.cancel).length:false);if(!g||d||!this._mouseCapture(f)){return true}this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet){this._mouseDelayTimer=setTimeout(function(){e.mouseDelayMet=true}, this.options.delay)}if(this._mouseDistanceMet(f)&amp;&amp;this._mouseDelayMet(f)){this._mouseStarted=(this._mouseStart(f)!==false);if(!this._mouseStarted){f.preventDefault();return true}}if(true===b.data(f.target, this.widgetName+&quot;.preventClickEvent&quot;)){b.removeData(f.target, this.widgetName+&quot;.preventClickEvent&quot;)}this._mouseMoveDelegate=function(h){return e._mouseMove(h)};this._mouseUpDelegate=function(h){return e._mouseUp(h)};b(document).bind(&quot;mousemove.&quot;+this.widgetName, this._mouseMoveDelegate).bind(&quot;mouseup.&quot;+this.widgetName, this._mouseUpDelegate);f.preventDefault();a=true;return true}, _mouseMove:function(d){if(b.browser.msie &amp;&amp;!(document.documentMode &gt;=9)&amp;&amp;!d.button){return this._mouseUp(d)}if(this._mouseStarted){this._mouseDrag(d);return d.preventDefault()}if(this._mouseDistanceMet(d)&amp;&amp;this._mouseDelayMet(d)){this._mouseStarted=(this._mouseStart(this._mouseDownEvent, d)!==false);(this._mouseStarted?this._mouseDrag(d):this._mouseUp(d))}return!this._mouseStarted}, _mouseUp:function(d){b(document).unbind(&quot;mousemove.&quot;+this.widgetName, this._mouseMoveDelegate).unbind(&quot;mouseup.&quot;+this.widgetName, this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;if(d.target==this._mouseDownEvent.target){b.data(d.target, this.widgetName+&quot;.preventClickEvent&quot;, true)}this._mouseStop(d)}return false}, _mouseDistanceMet:function(d){return(Math.max(Math.abs(this._mouseDownEvent.pageX-d.pageX), Math.abs(this._mouseDownEvent.pageY-d.pageY))&gt;=this.options.distance)}, _mouseDelayMet:function(d){return this.mouseDelayMet}, _mouseStart:function(d){}, _mouseDrag:function(d){}, _mouseStop:function(d){}, _mouseCapture:function(d){return true}})})(jQuery):&#160;jquery.js']]],
  ['widthx',['WidthX',['../class_o_v_r_main_menu.html#acfa3a06e35c763bbeaac22d0de3a1501',1,'OVRMainMenu']]],
  ['widthy',['WidthY',['../class_o_v_r_main_menu.html#adeebafaacd766df00bd95e3431fd4a8b',1,'OVRMainMenu']]],
  ['window',['window',['../jquery_8js.html#a3a1b34e910bfab09201cf4cd802439ea',1,'jquery.js']]],
  ['windowspos',['WindowsPos',['../struct_ovr_1_1_hmd_desc.html#ab8048ca822a0d020bdeb35b108c4bbfa',1,'Ovr.HmdDesc.WindowsPos()'],['../struct_ovr_1_1_hmd_desc___raw.html#a581dc38c4b4e893133dc4cc949f1df75',1,'Ovr.HmdDesc_Raw.WindowsPos()']]],
  ['working_5fdirectory',['WORKING_DIRECTORY',['../dialogmanager_8h.html#a2c949272911af8855d718bfc4ee81b61',1,'dialogmanager.h']]],
  ['writablemask',['WritableMask',['../namespace_ovr.html#ae0d3ebcd33d332d4a417426441b7ddc3aece506b12edef358d75a7f66081f516e',1,'Ovr']]],
  ['writecookie',['writeCookie',['../resize_8js.html#ad0822459a7d442b8c5e4db795d0aabb4',1,'resize.js']]]
];
